### ISSUE TITLE
should consider selenium/webdriver integration

### ISSUE THREAD

**Issue by adwu73** [sdesalas/trifleJS#20]
We have tried selenium/webdriver + phantomjs, however, this solution can not handle popup windows, alerts well. I hope trifleJS can support selenium integration in the future

**Comment by camisirli** [comment]
I really need selenium webdriver integration. Is there any update in this topic or can you suggest me alternative way?

**Comment by sdesalas** [comment]
Sorry. No plans to integrate selenium webdriver. Feel free to fork the project and do the integration if you really need it, you can shoot me a PR when you are finished.

**Comment by camisirli** [comment]
Thank you for your response. I would like to that but I do not have enough background in selenium also in C#. I am gonna check for alternative ways.
