### ISSUE TITLE
Trying to render with IE8 but it keeps showing IE10

### ISSUE THREAD

**Issue by stevenng** [sdesalas/trifleJS#22]
Hi guys,

Please let me know if I missed something, but I was typing in the command to emulate IE8, however the whatbrowser screenshot always shows that i'm currently using IE10.

TrifleJS.exe --debug --emulate=IE8 --render=http://whatbrowser.org/

Thanks!

**Comment by sdesalas** [comment]
Left to do: make sure there is another way to implement IE default ("standards mode"). For example accepting IE9_STANDARDS as emulation mode.

**Comment by sdesalas** [comment]
Added following `--emulate` options:

- `IE8_STANDARDS`
- `IE9_STANDARDS`, and 
- `IE10_STANDARDS`

These are there to support the default IE Auto-downgrade functionality that causes so much pain and confusion (the so-called "Standards" mode).
