### ISSUE TITLE
Screenshots Stop at Either Viewport Height Or 800px Height

### ISSUE THREAD

**Issue by DylanDonkersgoed** [sdesalas/trifleJS#29]
Screenshots taken with the page.render() function don't reach the height they should. 

I've tried with a couple different sites and for some reason render stops at either the viewport height (which seems logical on the surface but is not the behaviour of PhantomJS - it extends to the bottom of the page) or at 800px if I omit the height. I also get heights of 800px if I try to manually set the height as obtained from evaluating variants of this function:

    var D = document;
    var myHeight = Math.max(
        D.body.scrollHeight, D.documentElement.scrollHeight,
        D.body.offsetHeight, D.documentElement.offsetHeight,
        D.body.clientHeight, D.documentElement.clientHeight
    );

(from https://stackoverflow.com/questions/10173236/window-innerheight-ie8-alternative and various other places)

I tested the same function directly in the browser and it works to give page heights well over 800px.

**Comment by sdesalas** [comment]
Thanks for the extended explanation and the actual code for testing, these are very useful. Will test in both Debug and Release, not sure why the difference is there either.

**Comment by sdesalas** [comment]
Hi @DylanDonkersgoed,

Checked in c4c5ec4.

All good now as far as I can tell. Width and height looking good. I had to add those 50px in the end as there was no other way to remove the scrollbars.
