### ISSUE TITLE
Version printed as 1.7.0 while using release 0.4

### ISSUE THREAD

**Issue by paazmaya** [sdesalas/trifleJS#33]
```sh
triflejs --version
```
prints out `1.7.0` while the version installed is `0.4`.

**Comment by sdesalas** [comment]
Hi @paazmaya. 

Thats the version of phantom targetted by TrifleJS. 

To get the actual TrifleJS version you can use:

```
C:\> TrifleJS.exe
triflejs> trifle.version
0.5.0
```
I'm writing TrifleJS to be a drop-in replacement for phantom. But I see your logic in that its a bit odd seeing `1.7.0` in there. Maybe I'll change this sometime in the future.

**Comment by paazmaya** [comment]
Thank you for the explanation, @sdesalas

**Comment by sdesalas** [comment]
Hi @paazmaya,

I made changes to the codebase yesterday and incorporated this change. If you download the latest binary you'll get the trflejs version (0.5.0) instead.

**Comment by sdesalas** [comment]
NP! :)
