### ISSUE TITLE
getBoundingClientRect not working 

### ISSUE THREAD

**Issue by mkliu** [sdesalas/trifleJS#34]
I can't get anything from this, returned value is an empty object. I saw one of your test case actually is calling getBoundingClientRect(). 
              console.log(page.evaluate(function() {
                    var response;
                    var element = document.getElementById("ef");
                    // var element = document.documentElement;    not working either
                    var rect = element.getBoundingClientRect();
                    response += rect.left;
                    return response;
                }));

Any idea or suggestion on how do I debug this?

**Comment by sdesalas** [comment]
Can you send me the whole script? I'll try debug it.

**Comment by mkliu** [comment]
Here you go. If I want to debug myself, how should I do it? 

        var page = require('webpage').create(),
            system = require('system'),
            address, output, size;
        
        var output = "test.png";
        var address ="http://embed.plnkr.co/RxznuEsxVabaRVTGMbKa/preview";
        
        page.viewportSize = { width: 1800, height: 768 };
        page.open(address, function (status) {
            if (status !== 'success') {
                console.log('Unable to load the address!');
                phantom.exit();
            } else {
                window.setTimeout(function () {
                    console.log(page.evaluate(function() {
                        var response;
                        var element = document.getElementById("test");    // script error, getBoundingClientRect not defined
                        //var element = document.querySelector('H1');         // returns {}
                        //var element = document.documentElement            // returns {}
                        var rect = element.getBoundingClientRect();
                        return rect;
                    }));
                    page.render(output);
                    phantom.exit();
                }, 1000);
            }
        });

**Comment by sdesalas** [comment]
Perfect thanks :). Will be back with some more info on topic. 

In the meantime try to open up IE Developer tools and run the code in window.setTimeout() see what happens, in theory this should be no different to TrifleJS but if there is a difference I'll be able to tell you why.

**Comment by mkliu** [comment]
page is null, so i directly tried 
      document.getElementById("test")
This returns null. I tried on both IE10 (Server 2012) and IE11(Win8). I also tried on Chrome, it returns null too. But the element definitely exist, I modified the plunk to test that.

**Comment by mkliu** [comment]
Actually, i figured out why, the element is inside an iframe. So close the issue.
