### ISSUE TITLE
Evaluate doesn't return object

### ISSUE THREAD

**Issue by mkliu** [sdesalas/trifleJS#35]
The following script runs fine in phantom but not in trifleJS. Returning normal string is fine, but returning an object isn't.
		var page = require('webpage').create();
		var url = 'http://www.google.com/';

		page.open(url, function (status) {
		   var js = page.evaluate(function () {
		       return document;
		   });
		   console.log(JSON.stringify(js));
		   phantom.exit();
		});

**Comment by sdesalas** [comment]
Thanks @mkliu, this probably related to how IE and WebKit deal with host (browser) objects. The evaluate() call in TrifleJS should return simple JSON objects though, it's just that recursing through the host objects in IE tends to throw up all kinds of exceptions..

**Comment by mkliu** [comment]
heard the new IE is open sourced, not sure whether that's gonna make the story easier.

**Comment by sdesalas** [comment]
HI @mkliu,

Verified bug & checked in 62fa111, this should take care of the problem. I noticed host objects such as `window` and `document` return null. I dont think this is a bug but rather a problem trying to recurse over them to convert them to JSON.
