### ISSUE TITLE
SSL error ignore flag

### ISSUE THREAD

**Issue by lypanov** [sdesalas/trifleJS#36]
Currently when attempting to access a localhost https:// URL via render I get some nice dialog boxes, however, doing the same from within a script results in an instant "success" in the callback but no actual website is loaded. If this isn't something on your short term road map, do you have any pointers for next steps?

Thank you!

**Comment by sdesalas** [comment]
Hiya, haven't worked on this feature for a while and there is no unit test either so can't tell you for certain what it's doing.. will test again when I get a mo. Thanks for bringing it to my attention.

**Comment by sdesalas** [comment]
Hi @lypanov,

This should be working in the latest version of TrifleJS. Let me know how you go.

Steven
