### ISSUE TITLE
Javascript error popup on some websites

### ISSUE THREAD

**Issue by juliensobrier** [sdesalas/trifleJS#37]
Try this command:
TrifleJS.exe --render=https://www.zscaler.com/

There are Javascript error on the page. This creates 2 popups that need to be acknowledge manually. My Internet options have "Disable script debugging (Internet Explorer)" and "Disable script debugging (Other)" enabled, "Display a notification about every script error" disabled.

This might be enough to disable these warnings:
webBrowser.ScriptErrorsSuppressed = true;

**Comment by sdesalas** [comment]
Hiya @juliensobrier,

Thanks for the tip, I havent added the `.ScriptErrorsSuppressed = true` switch in as I wanted to be aware of any javascript errors that came up during development. 

I will make sure that the switch is added to the `Release` version of TrifleJS though, while keeping errors in `Debug`.

Cherio,
Steven
