### ISSUE TITLE
Use .NET mono and ship Trifle as a standalone distribution?

### ISSUE THREAD

**Issue by mkliu** [sdesalas/trifleJS#39]
I'm running into this problem when trying to deploy on different servers. Sometimes I need to install .NET framework, sometimes I need to install some distributable. Since .NET is open sources with mono runtime, Is it feasible to include them so trifle doesn't have to depend on external dependencies?

**Comment by sdesalas** [comment]
The distributable dependency should now be included in the [latest binary](https://github.com/sdesalas/trifleJS/raw/master/Build/Binary/TrifleJS.Latest.zip). For more info see [this post](https://github.com/sdesalas/trifleJS/issues/25#issuecomment-71375877).

I would not recommend using TrifleJS with .NET mono as you will find a host of other problems that arise from the different behaviour in [WebBrowser control](http://www.mono-project.com/docs/gui/winforms/webbrowser/) and in implementation of [InteropServices](http://www.mono-project.com/docs/advanced/pinvoke/).

**Comment by sdesalas** [comment]
Actually on that I need to remove the message asking for the distributables to be installed now they are bundled up... reopening

**Comment by sdesalas** [comment]
If you want to do this yourself just comment out lines [223-234 in Program.cs](https://github.com/sdesalas/trifleJS/blob/master/Program.cs#L223)

**Comment by sdesalas** [comment]
Hi @mkliu,

It would be great if you can give a pointer as to how the bundling up of VC9 dependencies worked with your various deployments, I am always short of time to test and anything you can save me would be much appreciated.

Ta!!

**Comment by mkliu** [comment]
I don't have a pointer, just a thought since .NET is going open source. Let me explore once I have some free time. But I'm expecting to see some weird problems coz fiddler on linux which was based on mono was awful.

**Comment by sdesalas** [comment]
No problems. Please read the wiki, there is an FAQ section there. Many ppl ask me if trifleJS will work on Linux/OSX, the short answer is no. 

However I notice you do some other work with Docker, it's worth waiting for windows dockerization which is supported in new OSs sometime down the line..

**Comment by mkliu** [comment]
Yup, I'm waiting for that excite moment too, lol
