### ISSUE TITLE
Error while obtaining navigator info - IE8

### ISSUE THREAD

**Issue by sdesalas** [sdesalas/trifleJS#40]
```
C:\TrifleJS.Latest (1)>TrifleJS.exe -u

============================================
TrifleJS -- Unit Tests
============================================
 (0,0): Object reference not set to an instance of an object.
bootstrap.js (82,29): Value cannot be null.
Parameter name: value
test/unit/tools.js (64,1): ReferenceError: console is not defined

Press any key to finish...
```

**Comment by sdesalas** [comment]
Only seems to be happening in XP/IE8

**Comment by tejacques** [comment]
Not sure if this will help you track it down, but I had this same error occur when running TrifleJS.0.4 on win7-ie8 32bit (Modern.IE VM). Using TrifleJS.Latest the problem went away.

**Comment by sdesalas** [comment]
Hi @tejacques. Thanks for the tip. Yep seems like this is related to IE version. Will keep an eye out and fix when I get a chance.

**Comment by sdesalas** [comment]
This was being caused when parsing native IE Host objects using JSON.stringify(). Should be fixed now.
