### ISSUE TITLE
Window SetTimeout / SetInterval don't work when building from source

### ISSUE THREAD

**Issue by tejacques** [sdesalas/trifleJS#46]
This may be related to VS2013 rather than trifle, but when I take a fresh checkout, open the solution in VS 2013, and run (in debug mode) TrifleJS.exe examples/countdown.js, I get the following error:

```
bootstrap.js (53,28): TypeError: Object #<Object> has no method 'SetInterval'
```

**Comment by sdesalas** [comment]
Thanks @tejacques 

Seems like a problem with recent changes to bootstrap.js, investigating..

S

**Comment by sdesalas** [comment]
I think this is fine now. Let me know.
