### ISSUE TITLE
TriffleJS --render fails on http://livedoor.com/

### ISSUE THREAD

**Issue by juliensobrier** [sdesalas/trifleJS#48]
Here is the output:

C:\...\trifleJS\bin\Debug>TrifleJS.exe --debug --render=http://livedoor.com/
TrifleJS.exe --debug --render=http://livedoor.com/
Setting Version to IE11
Rendering http://livedoor.com/...
WebBrowser#DocumentCompleted
Render(,)...
Ratio: 1
Width: 1007
Height: 1045
Screenshot rendered to file: livedoor.com.png
WebBrowser#DocumentCompleted
Render(,)...
Ratio: 1
Width: 1007
Height: 1045
Screenshot rendered to file: livedoor.com.png

Then it hangs. 

With more debugging, I caught this error message:
 System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at System.Windows.Forms.UnsafeNativeMethods.IHTMLWindow2.GetDocument()
   at System.Windows.Forms.HtmlWindow.get_Document()
   at TrifleJS.API.Modules.WebPage._evaluate(String function, Object[] args)

The excpetion happemns inside the check for CurrentFrame.Document != null

If you trap the exception inside _evaluate and wait long enough, the page will load completely and a screenshot can be taken.

**Comment by sdesalas** [comment]
Hiya, 

Thanks for the example and debug info. Will chase up when I get a mo.

**Comment by rajeshpaddy** [comment]
I'm having an issue with trifflejs similar to what is mentioned in this old post - https://github.com/ariya/phantomjs/issues/10619.

I'm setting a viewport width of 1420 and height of 800. But the rendered image takes the width correctly but the height is 10425. This makes the document very narrow. I would use clipRect if that works?. Do you know when clipRect will be available for trifflejs?

**Comment by sdesalas** [comment]
Hi @rajeshpaddy,

Can you copy/paste your testing script?

Thanks!

**Comment by rajeshpaddy** [comment]
var page = require('webpage').create();

page.zoomFactor=1;

page.onLoadFinished = function(e) {
     setTimeout(function(){
      page.render('msn.jpg',{quality:50});
      phantom.exit();},30000);
 };
page.viewportSize={width:1420,height:800};
console.log(page.viewportSize);
page.localT1oRemoteUrlAccessEnabled =true;

setTimeout(page.open('http://www.msn.com', function() {}),30000);
![msn](https://cloud.githubusercontent.com/assets/4166787/6657562/1e65a252-cb0d-11e4-9a0a-3a79add43283.jpg)

**Comment by rajeshpaddy** [comment]
##### In the above example the height is coming out as 5344. I expect it to 800.

**Comment by sdesalas** [comment]
Screenshot and test script received with thanks. Will get to it as soon as I can turn attention back to rendering functionality.

By the way this is related to `page.viewportSize`, which is a separate issue to one logged by @juliensobrier, in the future kindly open a separate ticket. Thanks.

**Comment by sdesalas** [comment]
Hi @juliensobrier.

Sorry for taking so long to get back, I think your issue should have been fixed after commit 125e7a0. This was repairing a call to `window.navigator` (using `page._evaluate()`) before the document had been initialized. Could you try again?

Thanks!

**Comment by sdesalas** [comment]
HI @rajeshpaddy, @juliensobrier.

Try your scripts after this fix, should help when rendering websites.

BTW @rajeshpaddy. I'm still to look into `page.viewportSize`, I have a feeling that the current functionality is the same as phantomJS (ie that rendered screenshots are not limited by viewport size but always render the whole page). I could be wrong though..

**Comment by sdesalas** [comment]
Hi @rajeshpaddy,

I just checked phantomJS and the script you sent me outputs a file `msn.jpg' that is 1420 x 2444. There is no issue here.. just your own expectation (although I have to admit this is what I thought phantom would do originally when I first wrote the API).

**Comment by juliensobrier** [comment]
@sdesalas http://livedoor.com/ still hangs TriffleJS

**Comment by sdesalas** [comment]
Seems ok for me, try using the `--render=http://livedoor.com` option.

    D:\Software\TrifleJS>TrifleJS.exe --render=http://livedoor.com
    Rendering http://livedoor.com...
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png
    Screenshot rendered to file: livedoor.com.png

    D:\Software\TrifleJS>

I have to do a bit of work on the event listeners (this is firing many times - probably due to iframes on adverts) but its rendering ok as far as I can tell (the output png looks good). I haven't done work on the `page.open()` `page.render()`, and have the feeling that the hanging will still apply if you execute a JS script to do this, however the availability of `--render` option means it'll be quicker to fix this.
