### ISSUE TITLE
window.callPhantom and unhandled error logging are not available until onload event fires.

### ISSUE THREAD

**Issue by tejacques** [sdesalas/trifleJS#50]
### Bug

Since these are set up on `DocumentCompleted`, the page has already run it's JavaScript and they are not available until the `onload` event has fired.

#### Steps to reproduce

test_callPhantom.js
```.js
var page = require('webpage').create();
page.onCallback = function(data) {
  console.log('CALLBACK: ' + JSON.stringify(data));
  // Prints 'CALLBACK: { "hello": "world" }'
};
page.open('http://path/to/below/file', function(status) {
  phantom.exit();
});
```

```.html
<!DOCTYPE html>
<html>
  <head>
    <script>
      // This should log as an unhandled error with:
      //    IE:http://path/to/file/below(13): 'nonexistentVariable' is undefined
      nonexistentVariable.shouldFail();
    </script>
    <script>
      // This should callPhantom successfully and print
      //    'CALLBACK { "hello": "world" }'
      window.callPhantom({hello: "world"});
    </script>
  </head>
  <body>
  </body>
</html>
```

#### Expected Output
```
IE:http://path/to/file/below(13): 'nonexistentVariable' is undefined
CALLBACK { "hello": "world" }
```

#### Actual Output
```
```

**Comment by tejacques** [comment]
I have a fix for this I'm happy to submit a PR for. Wanted to get feedback on the first one though since adding more commits to my master branch will automatically add them to that PR.

Also, fixing this issue lead me to discover bug #51.

**Comment by sdesalas** [comment]
Thanks @tejacques, I agree its better this way. Just have to check unit tests after doing the merge. Will get to this after more delicate work on page.onCallback.

**Comment by sdesalas** [comment]
I've integrated this functionality into 'Naviged' event as you suggested, thanks for picking this up.

Just need to add a couple of unit tests for page.onError.

**Comment by sdesalas** [comment]
Hi @tejacques,

Did you manage to get JS error handlers to fire at all using `browser.Document.Window.Error += delegate(object obj, HtmlElementErrorEventArgs e)`?, I had to give up on this approach which worked last time I look at it about a year ago. Instead I'm using injected javascript to capture `window.onerror`, which works more predictably.

Fix is ready, feel free to take a look and provide any comments. Ta.

**Comment by tejacques** [comment]
Pretty much all I had to do to get it to work in some simple tests was moving `browser.Document.Window.Error += delegate(object obj, HtmlElementErrorEventArgs e)` to the `Navigated` event.

**Comment by sdesalas** [comment]
Hmm that didnt work for me, I wonder if its different OS or IE version (I'm Win7 x86 running IE11)
