### ISSUE TITLE
window.callPhantom doesn't trigger page.onCallback after page.load

### ISSUE THREAD

**Issue by tejacques** [sdesalas/trifleJS#51]
### Bug

After calling `page.open`, `page.onCallback` doesn't trigger when `window.callPhantom` is called. It works from a newly created page, but that's it.

#### Steps to reproduce

test_onCallback.js
```.js
var webPage = require('webpage');
var page = webPage.create();
page.onCallback = function(data) {
  console.log('CALLBACK: ' + JSON.stringify(data));
  // Prints 'CALLBACK: { "hello": "world" }'
};
page.evaluate(function () {
    callPhantom({ hello: 'world' });
});
page.open('about:blank', function (status) {
    page.evaluate(function () {
        callPhantom({hello : 'back'});
    });
    phantom.exit();
});
```

#### Expected Output
```
CALLBACK: {"hello":"world"}
CALLBACK: {"hello":"back"}
```

### Actual Output (with: browser.ScriptErrorsSuppressed = false)
```
CALLBACK: {"hello":"world"}
Object doesn't support property or method 'xdebug'
```

Sometime between when the page is created, and a url is opened the ObjectForScripting becomes inaccessible in the window via external.

**Comment by tejacques** [comment]
I tracked this down to being caused by this line:

```.cs
this.browser.InitialiseOLE();
```

I'm not sure why this occurs, but if you use this, it makes the `ObjectForScripting` inaccessible after navigating.

**Comment by tejacques** [comment]
Do you have a good test case for this? I have this in a state where the AuthenticateProxy event is being fired and the ObjectForScripting object is accessible, but I don't have a good test file to see if Authenticating really works.

**Comment by sdesalas** [comment]
Hi @tejacques,

I noticed this behaviour as well and decided to postpone the bugfix til I deal with some of the CLI options such as proxy authentication. As you mentioned below these behaviours are linked but its hard to get a good test case running as TrifleJS does not have an internal proxy built in to create a test case with, and thus debugging is tedious and painful. Anyway thanks for bringing to my attention again.. S

**Comment by sdesalas** [comment]
Looking at command line proxies that I can incorporate into my unit tests, since phantoms ChildProcess functionality is up and running I can just spin off two sub-processes proxy.exe and a `triflejs.exe --proxy=address:port` and see what the output is for the latter.

**Comment by tejacques** [comment]
Awesome! Once I can properly test this I'll submit a PR.

**Comment by sdesalas** [comment]
FYI: Proxy authentication will be down for a while, I need to knock it out as this is higher priority.

**Comment by tejacques** [comment]
No worries. Let me know if there's anything I can update / fix / tweak on any of the issues I've submitted. I'd love to help get some of this stuff fixed upstream.

**Comment by sdesalas** [comment]
Should be working now. Only thing is getting the proxy authentication working but for that I have to write some proxy code to run unit tests with. Ta!
