### ISSUE TITLE
Can trifleJS use Chakra instead of V8?

### ISSUE THREAD

**Issue by masi** [sdesalas/trifleJS#54]
It seems a bit odd to use Chrome's JS engine instead of IE's one.

This one here claims to be able to embed Chakra:

https://github.com/Taritsyn/MsieJavaScriptEngine

MS itself seems to support officially Chakra only via IE11 :(

https://msdn.microsoft.com/en-us/library/dn249673%28v=vs.94%29.aspx
http://www.panopticoncentral.net/2013/07/02/introducing-jsrt-embedding-javascript-on-windows/

IMHO it would be great to use Chakra to be able to have a real test run for the browser as the JS engine is a vital part of the *ahem* browsing experience.

Cheers,
Masi

**Comment by tejacques** [comment]
I'm not sure if this answers your question, but trifleJS only uses V8 to run script files which talk to a web browser. Inside of the browser it will run that version of IE's native JS engine.

**Comment by masi** [comment]
Yes, it does. 

"A headless Internet Explorer browser using the .NET WebBrowser Class with a Javascript API running on the V8 JavaScript Engine."

This so prominently features V8 that I was mislead.

**Comment by sdesalas** [comment]
Hi @masi:

https://github.com/sdesalas/trifleJS/wiki#internet-explorer-has-a-different-javascript-engine-how-can-you-be-running-ie-with-the-v8-engine
