### ISSUE TITLE
Question: Any plans to make this work outside of windows?

### ISSUE THREAD

**Issue by fearphage** [sdesalas/trifleJS#56]
This would be a really powerful tool to use in continuous integration environment. Do you have any plans to support non-windows platforms?

**Comment by sdesalas** [comment]
HI @fearphage,

Thanks for the interest. Completely agree with you, the whole point of TrifleJS is to use it in CI or similar automation environment.

Unfortunately IE is not available in other operating systems. The [wiki contains an FAQ](https://github.com/sdesalas/trifleJS/wiki#are-you-planning-to-suport-linuxosx) with similar questions/answers on the topic.
