### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by wx-chevalier** [sdesalas/trifleJS#61]
![image](https://cloud.githubusercontent.com/assets/5803001/14236624/eb45c1c2-fa4a-11e5-879a-663b4acf8b04.png)

I run it in Windows 7 X64 : 6.1.7601.2.1.0.256.1

And it reported that System.IO.FileNotFoundException Exception.

**Comment by sdesalas** [comment]
Thanks for the bug report. Looks simlar to 25, can you take a look?
